/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle.template;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }

    /**
     * Adds 2 integers
     * @param a the first integer to be added
     * @param b the second integer to be added
     * @return the sum of a and b
     */
    public int sum(int a, int b) {
        //Your code here
        return 0;
    }
}
