/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle.template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    private App classUnderTest;

    @BeforeEach
    void setup() {
        classUnderTest = new App();
    }

    @Test
    void successfulTest() {
        assertEquals(3,classUnderTest.sum(1, 2));
    }

    @Test
    void failedTest() {
        assertNotEquals(0, classUnderTest.sum(1, 2));
    }
}
