/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle.template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    private App classUnderTest;

    @BeforeEach
    void setup() {
        classUnderTest = new App();
    }

    @Test
    void test1() {
        assertEquals(3,classUnderTest.sum(1, 2));
    }

    @Test
    void test2() {
        assertEquals(4,classUnderTest.sum(2, 2));
    }

    @Test
    void test3() {
        assertEquals(3,classUnderTest.sum(0, 3));
    }

    @Test
    void test4() {
        assertEquals(2,classUnderTest.sum(4, -2));
    }

    @Test
    void test5() {
        assertEquals(0,classUnderTest.sum(0, 0));
    }
}
